services:
  portfolio-frontend:
    build: .
    container_name: portfolio-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    networks:
      - portfolio-network
    environment:
      - NODE_ENV=production
    volumes:
      - ./logs:/var/log/nginx

networks:
  portfolio-network:
    driver: bridge

volumes:
  logs: